name: Validar nome da branch

on:
  pull_request:
    branches:
      - "*"

jobs:
  check-branch-name:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar nome da branch
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          echo "Nome da branch: $BRANCH_NAME"
          
          PATTERN="^(feature|bugfix|release|hotfix|docs|develop)/.*$"
          
          # Verifica se o nome contém espaços
          if [[ "$BRANCH_NAME" =~ \  ]]; then
            echo "🚨 Nome da branch inválido: '$BRANCH_NAME'. O nome da branch não pode conter espaços."
            exit 1
          fi

          # Verifica se o nome segue o padrão esperado
          if [[ ! "$BRANCH_NAME" =~ $PATTERN ]]; then
            echo "🚨 Nome de branch inválido: '$BRANCH_NAME'. O nome da branch deve seguir o padrão: [tipo]/[finalidade]/[nome-da-branch], onde [tipo] é 'feature', 'bugfix', 'release', 'hotfix', 'docs' ou 'develop'."
            exit 1
          fi
